```{r}

source('../seurat/cellHashingFunctions.R')

#Relatively good input.  Several outlier cells with extremely high counts.
barcodeFile <- 'cellHashing/247-1-hashTagCounts.txt'

#Extremely high doublets
#barcodeFile <- 'cellHashing/267-1-citeSeqCounts.txt'

#barcodeFile <- 'cellHashing/267-2-citeSeqCounts.txt'

#barcodeFile <- 'cellHashing/253-1-citeSeqCounts.txt'

#fails both callers.  probably many negative cells
barcodeFile <- 'cellHashing/260-4-HTO_cellHashingRawCounts.txt'
finalCallFile <- 'finalCalls.txt'

```

# Basic QC and Filtering on input:

```{r QC}

barcodeData <- processCiteSeqCount(barcodeFile)
if (nrow(barcodeData) == 0) {
  stop('No passing cells')
}

generateQcPlots(barcodeData)


```


# Using Seurat:

```{r Seurat}


sc <- generateCellHashCallsSeurat(barcodeData)


```

# Using MULTI-seq Classifier:

```{r MULTI-seq}


mc <- generateCellHashCallsMultiSeq(barcodeData, showTSNE = F)


```



```{r ProcessCalls}

dt <- processEnsemblHtoCalls(mc, sc, barcodeData, outFile = finalCallFile)


```